### ISSUE TITLE
docs: CSS 경로 수정 및 BEM 명명 규칙 수정 팁 공유

### ISSUE THREAD

**Issue by nickhealthy** [GeumZzoks/universeStay#59]
### 작업하시는데 고통 받고 계신거 같아 찾아봤습니다!!😭

**인텔리제이 기능을 이용한 것인데 아래 이미지를 참고해주세요!** 그럼 화이탱!!🚀👍
~~왜 이제서야 알려주냐고 하실 분이 계시다면.. 아니 그렇게 자주 말씀하시는 분께.. 저도 이 기능 없이 노가다 했어용..^^;~~
<br>

<img width="1728" alt="스크린샷 2023-11-28 오후 11 34 48" src="https://github.com/GeumZzoks/universeStay/assets/66216102/912dcbd9-208e-4063-9700-f52a62bb75cd">

**Comment by hanna-ryu** [comment]
와!!!!!!!

**Comment by jinkwon9301** [comment]
굿ㅎㅎ
